services:
  - type: web
    name: paperflow-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements-minimal.txt && python test_app.py
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: paperflow-frontend
          property: host
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false